### ISSUE TITLE
Make emoji tomatoes optional and activate with a command line

### ISSUE THREAD

**Issue by JaDogg** [JaDogg/pydoro#45]
Checking to see if we can write tomato emoji to terminal doesn't seem to work on Windows (normal console cmd.exe) and other various terminals.

Use a command line option such as `pydoro --emoji` to activate it.

NOTE: This wasn't a bug with the merge request sent by a contributor. Rather a bug in the requirement github issue I created 😭

**Comment by ZlatSic** [comment]
The reason why this doesn't work on Windows' cmd might be because unicode is not enabled. You might want to try playing around with some of [these answers](https://superuser.com/questions/487819/how-do-i-view-unicode-characters-on-command-prompt), change registries according to them and see if emojis can be printed then.

I'd like to try this one out, but I don't really get what you mean by "write tomato emoji to terminal" - where exactly would you like the emoji to be?

**Comment by JaDogg** [comment]
@ZlatSic it indeed work on the new `Microsoft Terminal` but not the `cmd.exe`. It's also working fine on OS X. So it would be better to make it optional. So people who want (And it works) can use it.
